### ISSUE TITLE
widget with screen shot summary does not work for GitHub Readme

### ISSUE THREAD

**Issue by lopezdp** [codersrank-org/summary-widget#12]
The widget using the link below does not work for GitHub README and it doesnt work from browser:

`https://cr-ss-service.azurewebsites.net/api/ScreenShot?widget=summary&username=GITHUB_USERNAME`

I tried working with issue #5 and the solution for the the issue doesnt work either - neither does caching as I do not control request headers, I just want to use in the README.

How can I make it work in a basic implementation using my username?

**Comment by peti2001** [comment]
Hi @lopezdp,

Thanks for reporting it. Now it is supposed to be fixed.
