### ISSUE TITLE
Badges dont render

### ISSUE THREAD

**Issue by fwolfst** [codersrank-org/summary-widget#3]
Following https://docs.codersrank.io/widgets/summary-widget when I create a page with
```html
<script src="https://unpkg.com/@codersrank/summary@0.9.10/codersrank-summary.min.js"></script>
<codersrank-summary username="fwolfst" badges=2 branding="false" layout="vertical"></codersrank-summary>
```
- it does not display any badges. Am I missing something (in which case the doc should be updated) or is it a bug?

**Comment by peti2001** [comment]
When I check your public profile https://profile.codersrank.io/user/fwolfst I cannot see the badges either. You might disabled them. Can you check, please?

**Comment by fwolfst** [comment]
@peti2001 Indeed. But if I try to move badges to the "highlighted badges" section on https://profile.codersrank.io/account/edit-badges it tellse me "Could not update badge. Please try again later.".

**Comment by fwolfst** [comment]
@peti2001 Indeed. But if I try to move badges to the "highlighted badges" section on https://profile.codersrank.io/account/edit-badges it tells me "Could not update badge. Please try again later.".

(400 Bad Request, `detail: "Invalid amount of highlighted badges"`)

**Comment by fwolfst** [comment]
@peti2001 The issue persists (error when trying to manage my highlighted badges). Should I report this upstream in a different repository?

**Comment by peti2001** [comment]
Hi @fwolfst,
It is supposed to be fixed. Can you please have a look at it?

**Comment by fwolfst** [comment]
Did only a shallow test, but yes - looks good now. Thanks.
